In [5]:
import numpy as np

In [9]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

array1: [1 2 3 4 5 6 7 8 9]


In [10]:
# index는 0부터 시작하므로 array1[2]는 3번 째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

value: 3
<class 'numpy.int64'>


In [12]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [13]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [14]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])

(row=0, col=0) index 가리키는 값: 1


In [17]:
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])

(row=0, col=1) index 가리키는 값: 2


In [18]:
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])

(row=1, col=0) index 가리키는 값: 4


In [19]:
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

(row=2, col=2) index 가리키는 값: 9


In [20]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [21]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])

array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]


In [23]:
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])

array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]


In [24]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)
